### ISSUE TITLE
"value io is not part of chisel3.Bundle{....}"

### ISSUE THREAD

**Issue by erlingrj** [PeterAaser/RISCV-FiveStage#2]
I am experiencing the issue described here: https://github.com/freechipsproject/chisel3/issues/606.

btw I am defining io's like:
val io = IO(new Bundle { ... })

The proposed fix for it is already part of build.sbt  (adding -Xsource:2.11 to the scalacOptions. Any ideas? I am using Ubuntu 18.04

erling@ubuntu-master:~/ntnu/RISCV-FiveStage$ ./sbt.sh 
[info] Loading global plugins from /home/erling/.sbt/1.0/plugins
[info] Loading project definition from /home/erling/ntnu/RISCV-FiveStage/project
[info] Loading settings from build.sbt ...
[info] Set current project to FiveStage (in build file:/home/erling/ntnu/RISCV-FiveStage/)
[info] sbt server started at local:///home/erling/.sbt/1.0/server/13dda7bff0a609c2fc4b/sock
sbt:FiveStage> about
[info] This is sbt 1.1.0
[info] The current project is ProjectRef(uri("file:/home/erling/ntnu/RISCV-FiveStage/"), "riscv-fivestage") 2.0.0
[info] The current project is built against Scala 2.12.8
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.4
sbt:FiveStage> 
sbt:FiveStage> settings -V

This is a list of settings defined for the current project.
It does not list the scopes the settings are defined in; use the 'inspect' command for that.

  apiURL                         Base URL for API documentation.
  appConfiguration               Provides access to the launched sbt configuration, including the ScalaProvider, Launcher, and GlobalLock.
  appResolvers                   The resolvers configured for this application by the sbt launcher.
  artifact                       Describes an artifact.
  artifactClassifier             Sets the classifier used by the default artifact definition.
  artifactName                   Function that produces the artifact name from its definition.
  artifactPath                   The location of a generated artifact.
  artifacts                      The artifact definitions for the current module.  Must be consistent with packagedArtifacts.
  autoAPIMappings                If true, automatically manages mappings to the API doc URL.
  autoCompilerPlugins            If true, enables automatically generating -Xplugin arguments to the compiler based on the classpath for the plugin configuration.
  autoGeneratedProject           If it exists, represents that the project (and name) were automatically created, rather than user specified.
  autoScalaLibrary               Adds a dependency on scala-library if true.
  baseDirectory                  The base directory.  Depending on the scope, this is the base directory for the build, project, configuration, or task.
  bgCopyClasspath                Copies classpath on bgRun to prevent conflict.
  bgJobService                   Job manager used to run background jobs.
  buildDependencies              Definitive source of inter-project dependencies for compilation and dependency management.
	This is populated by default by the dependencies declared on Project instances, but may be modified.
	The main restriction is that new builds may not be introduced.
  checksums                      The list of checksums to generate and to verify for dependencies.
  classDirectory                 Directory for compiled classes and copied resources.
  classpathOptions               Configures handling of Scala classpaths.
  classpathTypes                 Artifact types that are included on the classpath.
  cleanKeepFiles                 Files or directories to keep during a clean. Must be direct children of target.
  cleanupCommands                Commands to execute before the Scala interpreter exits.
  compatibilityWarningOptions    Configures warnings around Maven incompatibility.
  compileOrder                   Configures the order in which Java and sources within a single compilation are compiled.  Valid values are: JavaThenScala, ScalaThenJava, or Mixed.
  configuration                  Provides the current configuration of the referencing scope.
  configurationsToRetrieve       An optional set of configurations from which to retrieve dependencies if retrieveManaged is set to true
  conflictManager                Selects the conflict manager to use for dependency management.
  conflictWarning                Configures warnings for conflicts in dependency management.
  connectInput                   If true, connects standard input when running a main class forked.
  crossPaths                     If true, enables cross paths, which distinguish input and output directories for cross-building.
  crossSbtVersions               The versions of Sbt used when cross-building an sbt plugin.
  crossScalaVersions             The versions of Scala used when cross-building.
  crossTarget                    Main directory for files generated by the build that are cross-built.
  crossVersion                   Configures handling of the Scala version when cross-building.
  defaultConfiguration           Defines the configuration used when none is specified for a dependency in ivyXML.
  dependencyOverrides            Declares managed dependency overrides.
  description                    Project description.
  developers                     List of developers implicated in the project
  docArtifactTypes               Ivy artifact types that correspond to javadoc artifacts. Used by IDEs to resolve these resources.
  enableBinaryCompileAnalysis    Writes the analysis file in binary format
  evictionWarningOptions         Options on eviction warnings after resolving managed dependencies.
  excludeDependencies            Declares managed dependency exclusions.
  excludeFilter                  Filter for excluding sources and resources files from default directories.
  exportJars                     Determines whether the exported classpath for this project contains classes (false) or a packaged jar (true).
  exportToInternal               The level of tracking for this project by the internal callers.
  extraLoggers                   A function that provides additional loggers for a given setting.
  fileInputOptions               Options that take file input, which may invalidate the cache.
  forceUpdatePeriod              Duration after which to force a full update to occur
  fork                           If true, forks a new JVM when running.  If false, runs in the same JVM as the build.
  history                        The location where command line history is persisted.
  homepage                       Project homepage.
  includeFilter                  Filter for including sources and resources files from default directories.
  initialCommands                Initial commands to execute when starting up the Scala interpreter.
  internalConfigurationMap       Maps configurations to the actual configuration used to define the classpath.
  isSnapshot                     True if the version of the project is a snapshot version.
  ivyConfigurations              The defined configurations for dependency management.  This may be different from the configurations for Project settings.
  ivyLoggingLevel                The logging level for updating.
  ivyPaths                       Configures paths used by Ivy for dependency management.
  ivyValidate                    Enables/disables Ivy validation of module metadata.
  ivyXML                         Defines inline Ivy XML for configuring dependency management.
  javaHome                       Selects the Java installation used for compiling and forking.  If None, uses the Java installation running the build.
  javaSource                     Default Java source directory.
  libraryDependencies            Declares managed dependencies.
  licenses                       Project licenses as (name, url) pairs.
  loadedBuild                    Provides access to the loaded project structure.  This is the information available before settings are evaluated.
  logBuffered                    True if logging should be buffered until work completes.
  logLevel                       The amount of logging sent to the screen.
  logManager                     The log manager, which creates Loggers for different contexts.
  makePomConfiguration           Configuration for generating a pom.
  managedDirectory               Directory to which managed dependencies are retrieved.
  managedResourceDirectories     List of managed resource directories.
  managedScalaInstance           Automatically obtains Scala tools as managed dependencies if true.
  managedSourceDirectories       Managed source directories, which contain sources generated by the build.
  maxErrors                      The maximum number of errors, such as compile errors, to list.
  moduleConfigurations           Defines module configurations, which override resolvers on a per-module basis.
  moduleName                     The name of the current module, used for dependency management.
  name                           Project name.
  normalizedName                 Project name transformed from mixed case and spaces to lowercase and dash-separated.
  offline                        Configures sbt to work without a network connection where possible.
  onLoadMessage                  Message to display when the project is loaded.
  organization                   Organization/group ID.
  organizationHomepage           Organization homepage.
  organizationName               Organization full/formal name.
  outputStrategy                 Selects how to log output when running a main class.
  overrideBuildResolvers         Whether or not all the build resolvers should be overridden with what's defined from the launcher.
  parallelExecution              Enables (true) or disables (false) parallel execution of tasks.
  pollInterval                   Interval between checks for modified sources by the continuous execution command.
  pomAllRepositories             If true, includes repositories used in module configurations in the pom repositories section.  If false, only the common repositories are included.
  pomExtra                       Extra XML to insert into the generated POM.
  pomIncludeRepository           Selects repositories to include in the generated POM.
  pomPostProcess                 Transforms the generated POM.
  projectID                      The dependency management descriptor for the current module.
  projectInfo                    Addition project information like formal name, homepage, licenses etc.
  publishArtifact                Enables (true) or disables (false) publishing an artifact.
  publishMavenStyle              Configures whether to generate and publish a pom (true) or Ivy file (false).
  resolvers                      The user-defined additional resolvers for automatically managed dependencies.
  resourceDirectories            List of all resource directories, both managed and unmanaged.
  resourceDirectory              Default unmanaged resource directory, used for user-defined resources.
  resourceGenerators             List of tasks that generate resources.
  resourceManaged                Default managed resource directory, used when generating resources.
  retrieveConfiguration          Configures retrieving dependencies to the current build.
  retrieveManaged                If true, enables retrieving dependencies to the current build.  Otherwise, dependencies are used directly from the cache.
  retrieveManagedSync            If true, enables synchronizing the dependencies retrieved to the current build by removed unneeded files.
  retrievePattern                Pattern used to retrieve managed dependencies to the current build.
  sbtBinaryVersion               Defines the binary compatibility version substring.
  sbtDependency                  Provides a definition for declaring the current version of sbt.
  sbtPlugin                      If true, enables adding sbt as a dependency and auto-generation of the plugin descriptor file.
  sbtResolver                    Provides a resolver for obtaining sbt as a dependency.
  sbtVersion                     Provides the version of sbt.  This setting should not be modified.
  scalaArtifacts                 Configures the list of artifacts which should match the Scala binary version
  scalaBinaryVersion             The Scala version substring describing binary compatibility.
  scalaCompilerBridgeSource      Configures the module ID of the sources of the compiler bridge.
  scalaHome                      If Some, defines the local Scala installation to use for compilation, running, and testing.
  scalaModuleInfo                Configures how Scala dependencies are checked, filtered, and injected.
  scalaOrganization              Organization/group ID of the Scala used in the project. Default value is 'org.scala-lang'. This is an advanced setting used for clones of the Scala Language. It should be disregarded in standard use cases.
  scalaSource                    Default Scala source directory.
  scalaVersion                   The version of Scala used for building.
  scmInfo                        Basic SCM information for the project.
  sourceArtifactTypes            Ivy artifact types that correspond to source artifacts. Used by IDEs to resolve these resources.
  sourceDirectories              List of all source directories, both managed and unmanaged.
  sourceDirectory                Default directory containing sources.
  sourceGenerators               List of tasks that generate sources.
  sourceManaged                  Default directory for sources generated by the build.
  sourcesInBase                  If true, sources from the project's base directory are included as main sources.
  startYear                      Year in which the project started.
  tags                           Attributes restricting concurrent execution of tasks.
  target                         Main directory for files generated by the build.
  taskTemporaryDirectory         Directory used for temporary files for tasks that is deleted after each task execution.
  testForkedParallel             Whether forked tests should be executed in parallel
  testFrameworks                 Registered, although not necessarily present, test frameworks.
  testResultLogger               Logs results after a test task completes.
  thisProject                    Provides the current project for the referencing scope.
  thisProjectRef                 Provides a fully-resolved reference to the current project for the referencing scope.
  trackInternalDependencies      The level of tracking for the internal (inter-project) dependency.
  transitiveClassifiers          List of classifiers used for transitively obtaining extra artifacts for sbt or declared dependencies.
  trapExit                       If true, enables exit trapping and thread management for 'run'-like tasks.  This is currently only suitable for serially-executed 'run'-like tasks.
  triggeredMessage               The message to show before triggered execution executes an action after sources change.
  unmanagedBase                  The default directory for manually managed libraries.
  unmanagedResourceDirectories   Unmanaged resource directories, containing resources manually created by the user.
  unmanagedSourceDirectories     Unmanaged source directories, which contain manually created sources.
  updateConfiguration            Configuration for resolving and retrieving managed dependencies.
  updateOptions                  Options for resolving managed dependencies.
  useJCenter                     Use JCenter as the default repository.
  version                        The version/revision of the current module.
  watch                          Continuous execution configuration.
  watchService                   Service to use to monitor file system changes.
  watchingMessage                The message to show when triggered execution waits for sources to change.

**Comment by PeterAaser** [comment]
What happens if you define the bundle first, instead of as an anonymous class inside the IO macro?

**Comment by erlingrj** [comment]
This turns out to be 100% my fault. I am working on ID.scala  and I hadnt noticed that
val decoder = Module(new Decoder).io
So the decoder object was actually the IO bundle and not the complete module, and when I tried to do: decoder.io.instruction I got that error message. Unfortunately I was led astray by previous bug-reports on the chisel3 repo with the same error message. 

Whats the reason for not doing:
val decoder = Module(new Decoder)

**Comment by PeterAaser** [comment]
Historically `Module` was the de facto way to make modules, so it made sense to use .io at declaration since it's the only thing we can interact with. With `MulitIOModule` becoming the standard this is a little more awkward, thus in the repo some modules have the `.io` when there is no testHarness.

It's just a tradeoff for saving some keystrokes
